### ISSUE TITLE
crm_action: actions lost on merge

### ISSUE THREAD

**Issue by miscs** [OCA/crm#88]
Hi, 

I am using odoo 8 with installed crm_action, which works quite well. The only problem I encountered ist that when I merge a lead with an existing opportunity all actions from the lead are lost (deleted).

Is this by design? When I convert a lead to a new opportunity the actions are still accessible from the newly created opportunity. 

Thanks!
Steve

**Comment by pedrobaeza** [comment]
This is not by design, but it's also a non covered-feature and debatable one. You want to have the actions from the lead, but others can say that the actions should be the ones from the opportunity (which is the current behavior).

If you want this behavior, develop it and propose it as a PR, and with a configurable parameter, for sure it will be accepted.

**Comment by miscs** [comment]
Thanks for your reply!

This even happens when I merge two leads, which is a wrong behaviour in my opinion.

I have made a small chance which keeps all actions on merge but without configurable parameter. Since the addon doesn't have a config-gui and I am not experienced with odoo development this is a bit out of scope for me :(Is there a way to have a parameter somewhere in the addon-files?

If you want a PR without configurable parameter, I can provide my change.

Thanks!

**Comment by pedrobaeza** [comment]
If you can provide the PR, it would be welcome.
